#!/bin/bash

if (($# != 2))
then
  printf "Usage: %s FILENAME TITLE\n" $0
  exit 1
fi


date=$(date +"%Y-%m-%d")

title=$2

filename=$date"-"$1".md"

if [ -f $filename ]
then
  printf "File %s exists already!\n" $filename
  exit 1
fi

printf -- "---\nlayout: post\ntitle: \"%s\"\ndate: %s\ncategories: blog\n---\n\n" "$title" "$date" > "$filename"

exit 0
